"""Markdown export (ARCHITECTURE §10.6, Phase 16).

Bundles a session's concepts, latest quiz, mastery scores, and (optionally) a
cheat-sheet into a single downloadable Markdown file. No third-party deps.
"""
from __future__ import annotations

import os

from studybuddy import store
from studybuddy.config import STUDYBUDDY_DB
from studybuddy.tracker import concept_scores, init_db, list_documents

_EXPORT_DIR = os.path.join(os.path.dirname(STUDYBUDDY_DB) or ".", "exports")


def export_markdown(session_id: str, include_summary: bool = False) -> str:
    """Write a Markdown study pack for `session_id`; return the file path."""
    init_db()
    concepts = store.get_concepts(session_id)
    quiz = store.get_latest_quiz(session_id)
    scores = concept_scores(session_id)
    docs = list_documents(session_id)

    lines: list[str] = [f"# StudyBuddy export — session `{session_id}`", ""]

    if docs:
        lines.append("## Documents")
        lines += [f"- **{d['name']}** (`{d['doc_id']}`)" for d in docs]
        lines.append("")

    if scores:
        lines.append("## Mastery")
        for s in scores:
            lines.append(
                f"- **{s['concept_name']}**: {s['correct']}/{s['attempts']} "
                f"({s['accuracy']:.0%}), mastery {s.get('mastery', 0):.0%}"
            )
        lines.append("")

    if concepts:
        lines.append("## Concepts")
        for c in concepts:
            terms = ", ".join(c.get("key_terms", []) or [])
            lines.append(f"### {c.get('name')}")
            lines.append(c.get("definition", ""))
            if terms:
                lines.append(f"_Key terms: {terms}_")
            lines.append("")

    if quiz:
        lines.append("## Latest quiz")
        for i, q in enumerate(quiz, 1):
            lines.append(f"**Q{i} ({q.get('question_type')}/{q.get('difficulty')}).** {q.get('prompt')}")
            for opt in q.get("options", []) or []:
                lines.append(f"  - {opt}")
            lines.append(f"  - _Answer:_ {q.get('answer')}")
            if q.get("explanation"):
                lines.append(f"  - _Why:_ {q.get('explanation')}")
            lines.append("")

    if include_summary and concepts:
        from studybuddy.agents.summarizer import make_summary

        lines.append("## Cheat sheet")
        lines.append(make_summary(session_id))
        lines.append("")

    lines.append("---")
    lines.append("_Generated by StudyBuddy — an educational aid; verify against your source material._")

    os.makedirs(_EXPORT_DIR, exist_ok=True)
    path = os.path.join(_EXPORT_DIR, f"studybuddy_{session_id}.md")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path
